namespace LocalizationKeys
{
	public class AccountServices
	{
		public const string LOGIN_POPUP_TITLE = "LOGIN_POPUP_TITLE";

		public const string LOGIN_POPUP_EMAIL_FIELD_LABEL = "LOGIN_POPUP_EMAIL_FIELD_LABEL";

		public const string LOGIN_POPUP_PASSWORD_FIELD_LABEL = "LOGIN_POPUP_PASSWORD_FIELD_LABEL";

		public const string LOGIN_POPUP_HINT_TEXT = "LOGIN_POPUP_HINT_TEXT";

		public const string LOGIN_POPUP_FORGOT_PASSWORD_BUTTON_LABEL = "LOGIN_POPUP_FORGOT_PASSWORD_BUTTON_LABEL";

		public const string LOGIN_POPUP_LOGIN_BUTTON_LABEL = "LOGIN_POPUP_LOGIN_BUTTON_LABEL";

		public const string LOGIN_POPUP_FORGOT_PASSWORD_TITLE = "LOGIN_POPUP_FORGOT_PASSWORD_TITLE";

		public const string LOGIN_POPUP_FORGOT_PASSWORD_HINT_TEXT = "LOGIN_POPUP_FORGOT_PASSWORD_HINT_TEXT";

		public const string LOGIN_POPUP_BACK_BUTTON_LABEL = "LOGIN_POPUP_BACK_BUTTON_LABEL";

		public const string LOGIN_POPUP_FORGOT_PASSWORD_SEND_BUTTON_LABEL = "LOGIN_POPUP_FORGOT_PASSWORD_SEND_BUTTON_LABEL";

		public const string LOGIN_POPUP_CREATE_PASSWORD_TITLE = "LOGIN_POPUP_CREATE_PASSWORD_TITLE";

		public const string LOGIN_POPUP_RE_ENTER_PASSWORD_FIELD_LABEL = "LOGIN_POPUP_RE_ENTER_PASSWORD_FIELD_LABEL";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_AGREEMENT_TEXT = "LOGIN_POPUP_CREATE_ACCOUNT_AGREEMENT_TEXT";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_TERMS_LINK_TEXT = "LOGIN_POPUP_CREATE_ACCOUNT_TERMS_LINK_TEXT";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_SPAM_HINT = "LOGIN_POPUP_CREATE_ACCOUNT_SPAM_HINT";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_CONFIRM_BUTTON_LABEL = "LOGIN_POPUP_CREATE_ACCOUNT_CONFIRM_BUTTON_LABEL";

		public const string LOGIN_POPUP_PASSWORDS_DO_NOT_MATCH_LABEL = "LOGIN_POPUP_PASSWORDS_DO_NOT_MATCH_LABEL";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_TITLE = "LOGIN_POPUP_CREATE_ACCOUNT_TITLE";

		public const string LOGIN_POPUP_RE_ENTER_EMAIL_FIELD_LABEL = "LOGIN_POPUP_RE_ENTER_EMAIL_FIELD_LABEL";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_HINT = "LOGIN_POPUP_CREATE_ACCOUNT_HINT";

		public const string LOGIN_POPUP_CREATE_ACCOUNT_WARNING = "LOGIN_POPUP_CREATE_ACCOUNT_WARNING";

		public const string LOGIN_POPUP_USE_EXISTING_BUTTON_LABEL = "LOGIN_POPUP_USE_EXISTING_BUTTON_LABEL";

		public const string LOGIN_POPUP_NEXT_BUTTON_LABEL = "LOGIN_POPUP_NEXT_BUTTON_LABEL";

		public const string NEW_VERSION_POPUP_TITLE = "NEW_VERSION_POPUP_TITLE";

		public const string NEW_VERSION_POPUP_CONTENTS = "NEW_VERSION_POPUP_CONTENTS";

		public const string NEW_VERSION_POPUP_UPDATE_BUTTON_LABEL = "NEW_VERSION_POPUP_UPDATE_BUTTON_LABEL";

		public const string NO_CONNECTION_POPUP_TITLE = "NO_CONNECTION_POPUP_TITLE";

		public const string NO_CONNECTION_POPUP_CONTENTS = "NO_CONNECTION_POPUP_CONTENTS";

		public const string NO_CONNECTION_PLAY_TUTORIAL_BUTTON_LABEL = "NO_CONNECTION_PLAY_TUTORIAL_BUTTON_LABEL";

		public const string LOADING_STATUS_LABEL = "LOADING_STATUS_LABEL";

		public const string GUEST_ACCOUNT_PREFIX = "GUEST_ACCOUNT_PREFIX";

		public const string PLAYER_NAME_PREFIX = "PLAYER_NAME_PREFIX";
	}
}
