namespace LocalizationKeys
{
	public class BuyCurrency
	{
		public const string BUY_GAS_POPUP_TITLE = "BUY_GAS_POPUP_TITLE";

		public const string BUY_JOULES_POPUP_TITLE = "BUY_JOULES_POPUP_TITLE";

		public const string BUY_CURRENCY_GUEST_WARNING_CONTINUE_BUTTON = "BUY_CURRENCY_GUEST_WARNING_CONTINUE_BUTTON";

		public const string BUY_CURRENCY_GUEST_WARNING_TITLE = "BUY_CURRENCY_GUEST_WARNING_TITLE";

		public const string BUY_CURRENCY_GUEST_WARNING_UPGRADE_BUTTON = "BUY_CURRENCY_GUEST_WARNING_UPGRADE_BUTTON";

		public const string BUY_CURRENCY_GUEST_WARNING_BODY = "BUY_CURRENCY_GUEST_WARNING_BODY";
	}
}
