namespace LocalizationKeys
{
	public class Error
	{
		public const string ERROR_INVALID_SESSION_TITLE = "ERROR_INVALID_SESSION_TITLE";

		public const string ERROR_INVALID_SESSION_BODY = "ERROR_INVALID_SESSION_BODY";

		public const string ERROR_INVALID_SESSION_BUTTON_LABEL = "ERROR_INVALID_SESSION_BUTTON_LABEL";

		public const string ERROR_DISCONNECTED_TITLE = "ERROR_DISCONNECTED_TITLE";

		public const string ERROR_DISCONNECTED_BODY = "ERROR_DISCONNECTED_BODY";

		public const string ERROR_DISCONNECTED_BUTTON_LABEL = "ERROR_DISCONNECTED_BUTTON_LABEL";

		public const string ERROR_GAME_CANCELED_TITLE = "ERROR_GAME_CANCELED_TITLE";

		public const string ERROR_GAME_CANCELED_BODY = "ERROR_GAME_CANCELED_BODY";

		public const string ERROR_GAME_CANCELED_BUTTON_LABEL = "ERROR_GAME_CANCELED_BUTTON_LABEL";
	}
}
