namespace LocalizationKeys
{
	public class FacebookSharing
	{
		public const string FACEBOOK_SHARE_BUTTON_LABEL = "FACEBOOK_SHARE_BUTTON_LABEL";

		public const string FACEBOOK_CONTACTING_STATUS = "FACEBOOK_CONTACTING_STATUS";

		public const string FACEBOOK_POST_TITLE = "FACEBOOK_POST_TITLE";

		public const string FACEBOOK_POST_ICON_CAPTION = "FACEBOOK_POST_ICON_CAPTION";

		public const string FACEBOOK_POST_LEVEL_FORMAT_STRING = "FACEBOOK_POST_LEVEL_FORMAT_STRING";

		public const string FACEBOOK_LOGIN_FAILED = "FACEBOOK_LOGIN_FAILED";

		public const string FACEBOOK_POST_SUCCESSFULL = "FACEBOOK_POST_SUCCESSFULL";

		public const string FACEBOOK_POST_FAILED = "FACEBOOK_POST_FAILED";

		public const string FACEBOOK_POST_RANK_FORMAT_STRING = "FACEBOOK_POST_RANK_FORMAT_STRING";
	}
}
