namespace LocalizationKeys
{
	public class Gearup
	{
		public const string GEARUP_CATEGORY_LOADOUT = "GEARUP_CATEGORY_LOADOUT";

		public const string GEARUP_CATEGORY_CHARACTER = "GEARUP_CATEGORY_CHARACTER";

		public const string GEARUP_CATEGORY_SKINS = "GEARUP_CATEGORY_SKINS";

		public const string GEARUP_CATEGORY_TAUNTS = "GEARUP_CATEGORY_TAUNTS";

		public const string GEARUP_CATEGORY_PRIMARY = "GEARUP_CATEGORY_PRIMARY";

		public const string GEARUP_CATEGORY_SECONDARY = "GEARUP_CATEGORY_SECONDARY";

		public const string GEARUP_CATEGORY_MELEE = "GEARUP_CATEGORY_MELEE";

		public const string GEARUP_CATEGORY_SPECIAL = "GEARUP_CATEGORY_SPECIAL";

		public const string GEARUP_CATEGORY_EQUIPMENT = "GEARUP_CATEGORY_EQUIPMENT";

		public const string GEARUP_CATEGORY_EQUIPMENT_1 = "GEARUP_CATEGORY_EQUIPMENT_1";

		public const string GEARUP_CATEGORY_EQUIPMENT_2 = "GEARUP_CATEGORY_EQUIPMENT_2";

		public const string GEARUP_CATEGORY_PRO_MODE = "GEARUP_CATEGORY_PRO_MODE";

		public const string GEARUP_NONE = "GEARUP_NONE";

		public const string GEARUP_MORE_INFO = "GEARUP_MORE_INFO";

		public const string GEARUP_GOLD_SKINS_DESCRIPTION = "GEARUP_GOLD_SKINS_DESCRIPTION";

		public const string GEARUP_UNAFFECTED_BY_EQUIPMENT = "GEARUP_UNAFFECTED_BY_EQUIPMENT";

		public const string GEARUP_EQUIPMENT_HEALTH_MODIFIER = "GEARUP_EQUIPMENT_HEALTH_MODIFIER";

		public const string GEARUP_EQUIPMENT_SPEED_MODIFIER = "GEARUP_EQUIPMENT_SPEED_MODIFIER";

		public const string GEARUP_EQUIPMENT_SPECIAL_MODIFIER = "GEARUP_EQUIPMENT_SPECIAL_MODIFIER";
	}
}
