namespace LocalizationKeys
{
	public class MatchingWait
	{
		public const string MATCHING_WAIT_TITLE = "MATCHING_WAIT_TITLE";

		public const string MATCHING_WAIT_USERS = "MATCHING_WAIT_USERS";

		public const string MATCHING_WAIT_TIME = "MATCHING_WAIT_TIME";

		public const string MATCHING_WAIT_TIME_WAITED = "MATCHING_WAIT_TIME_WAITED";

		public const string MATCHING_WAIT_TIME_UNAVAILABLE = "MATCHING_WAIT_TIME_UNAVAILABLE";

		public const string MATCHING_WAIT_CONNECTION_FAILED_TITLE = "MATCHING_WAIT_CONNECTION_FAILED_TITLE";

		public const string MATCHING_WAIT_CONNECTION_FAILED_MESSAGE = "MATCHING_WAIT_CONNECTION_FAILED_MESSAGE";

		public const string MATCHING_WAIT_CONNECTION_FAILED_CLOSE_BUTTON_LABEL = "MATCHING_WAIT_CONNECTION_FAILED_CLOSE_BUTTON_LABEL";

		public const string MATCHING_WAIT_FETCHING_WAIT_TIME = "MATCHING_WAIT_FETCHING_WAIT_TIME";

		public const string MATCHING_WAIT_SEARCHING_FOR_GAME = "MATCHING_WAIT_SEARCHING_FOR_GAME";
	}
}
