namespace LocalizationKeys
{
	public class OptionsPopup
	{
		public const string OPTIONS_POPUP_KEYBOARD_MOUSE = "OPTIONS_POPUP_KEYBOARD_MOUSE";

		public const string OPTIONS_POPUP_DOUBLE_TAP = "OPTIONS_POPUP_DOUBLE_TAP";

		public const string OPTIONS_POPUP_BUTTON_SHOOT = "OPTIONS_POPUP_BUTTON_SHOOT";

		public const string OPTIONS_POPUP_CONTROLS_LABEL = "OPTIONS_POPUP_CONTROLS_LABEL";

		public const string OPTIONS_POPUP_LOGIN_CREATE_LABEL = "OPTIONS_POPUP_LOGIN_CREATE_LABEL";

		public const string OPTIONS_POPUP_SIGN_OUT_LABEL = "OPTIONS_POPUP_SIGN_OUT_LABEL";

		public const string OPTIONS_POPUP_LOGGED_IN_AS = "OPTIONS_POPUP_LOGGED_IN_AS";

		public const string OPTIONS_POPUP_MUSIC_LABEL = "OPTIONS_POPUP_MUSIC_LABEL";

		public const string OPTIONS_POPUP_SENSITIVITY_LABEL = "OPTIONS_POPUP_SENSITIVITY_LABEL";

		public const string OPTIONS_POPUP_SOUND_EFFECTS_LABEL = "OPTIONS_POPUP_SOUND_EFFECTS_LABEL";
	}
}
