namespace LocalizationKeys
{
	public class PausePopup
	{
		public const string PAUSE_POPUP_BACK_BUTTON = "PAUSE_POPUP_BACK_BUTTON";

		public const string PAUSE_POPUP_BUTTON_SIZE_LABEL = "PAUSE_POPUP_BUTTON_SIZE_LABEL";

		public const string PAUSE_POPUP_EXIT_MATCH_BUTTON = "PAUSE_POPUP_EXIT_MATCH_BUTTON";

		public const string PAUSE_POPUP_MUSIC_LABEL = "PAUSE_POPUP_MUSIC_LABEL";

		public const string PAUSE_POPUP_SENSITIVITY_LABEL = "PAUSE_POPUP_SENSITIVITY_LABEL";

		public const string PAUSE_POPUP_SOUND_EFFECTS_LABEL = "PAUSE_POPUP_SOUND_EFFECTS_LABEL";

		public const string PAUSE_POPUP_OFF_LABEL = "PAUSE_POPUP_OFF_LABEL";

		public const string PAUSE_POPUP_ON_LABEL = "PAUSE_POPUP_ON_LABEL";

		public const string PAUSE_POPUP_SHOOT_BUTTON_LABEL = "PAUSE_POPUP_SHOOT_BUTTON_LABEL";

		public const string PAUSE_POPUP_KEYBOARD_AND_MOUSE_LABEL = "PAUSE_POPUP_KEYBOARD_AND_MOUSE_LABEL";

		public const string PAUSE_POPUP_DOUBLE_TAP_LABEL = "PAUSE_POPUP_DOUBLE_TAP_LABEL";

		public const string PAUSE_POPUP_CUSTOM_CONTROLS_LABEL = "PAUSE_POPUP_CUSTOM_CONTROLS_LABEL";

		public const string PAUSE_POPUP_DEFAULT_CONTROLS_LABEL = "PAUSE_POPUP_DEFAULT_CONTROLS_LABEL";

		public const string PAUSE_POPUP_ZOOM_TOGGLE_LABEL = "PAUSE_POPUP_ZOOM_TOGGLE_LABEL";

		public const string PAUSE_POPUP_DOUBLE_TAP_TOGGLE_LABEL = "PAUSE_POPUP_DOUBLE_TAP_TOGGLE_LABEL";

		public const string PAUSE_POPUP_RADAR_TOGGLE_LABEL = "PAUSE_POPUP_RADAR_TOGGLE_LABEL";

		public const string PAUSE_POPUP_CONTROL_SELECTION_LABEL = "PAUSE_POPUP_CONTROL_SELECTION_LABEL";
	}
}
