namespace LocalizationKeys
{
	public class PrivateMatching
	{
		public const string CREATE_MATCH_PICK_LEVEL_LABEL = "CREATE_MATCH_PICK_LEVEL_LABEL";

		public const string CREATE_MATCH_ARENA_NAME_FIELD_LABEL = "CREATE_MATCH_ARENA_NAME_FIELD_LABEL";

		public const string CREATE_MATCH_PASSWORD_FIELD_LABEL = "CREATE_MATCH_PASSWORD_FIELD_LABEL";

		public const string CREATE_MATCH_PASSWORD_OPTIONAL_LABEL = "CREATE_MATCH_PASSWORD_OPTIONAL_LABEL";

		public const string CREATE_MATCH_GAME_MODE_LABEL = "CREATE_MATCH_GAME_MODE_LABEL";

		public const string CREATE_MATCH_BACK_BUTTON_LABEL = "CREATE_MATCH_BACK_BUTTON_LABEL";

		public const string CREATE_MATCH_CREATE_BUTTON_LABEL = "CREATE_MATCH_CREATE_BUTTON_LABEL";

		public const string MATCH_LOBBY_POPUP_TITLE = "MATCH_LOBBY_POPUP_TITLE";

		public const string CREATE_MATCH_ROOM_FAILED_STATUS = "CREATE_MATCH_ROOM_FAILED_STATUS";

		public const string MATCH_LOBBY_INCORRECT_PASSWORD_STATUS = "MATCH_LOBBY_INCORRECT_PASSWORD_STATUS";

		public const string MATCH_LOBBY_NO_SEARCH_RESULTS_STATUS = "MATCH_LOBBY_NO_SEARCH_RESULTS_STATUS";

		public const string MATCH_LOBBY_FAILED_TO_JOIN_STATUS = "MATCH_LOBBY_FAILED_TO_JOIN_STATUS";

		public const string CREATE_MATCH_ROOM_ALREADY_EXISTS = "CREATE_MATCH_ROOM_ALREADY_EXISTS";

		public const string CREATE_MATCH_NO_ROOM_NAME = "CREATE_MATCH_NO_ROOM_NAME";

		public const string MATCH_LOBBY_KICKED_PLAYER_STATUS = "MATCH_LOBBY_KICKED_PLAYER_STATUS";
	}
}
