namespace LocalizationKeys
{
	public class ReputationNegativeExplaination
	{
		public const string REPUTATION_NEGATIVE_EXPLAINATION_TITLE = "REPUTATION_NEGATIVE_EXPLAINATION_TITLE";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_BODY_1 = "REPUTATION_NEGATIVE_EXPLAINATION_BODY_1";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_BODY_2 = "REPUTATION_NEGATIVE_EXPLAINATION_BODY_2";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_AFK = "REPUTATION_NEGATIVE_EXPLAINATION_AFK";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_OFFENSIVE_NAME = "REPUTATION_NEGATIVE_EXPLAINATION_OFFENSIVE_NAME";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_HARASSMENT = "REPUTATION_NEGATIVE_EXPLAINATION_HARASSMENT";

		public const string REPUTATION_NEGATIVE_EXPLAINATION_HACKER = "REPUTATION_NEGATIVE_EXPLAINATION_HACKER";
	}
}
