namespace LocalizationKeys
{
	public class ReputationPositiveExplaination
	{
		public const string REPUTATION_POSITIVE_EXPLAINATION_TITLE = "REPUTATION_POSITIVE_EXPLAINATION_TITLE";

		public const string REPUTATION_POSITIVE_EXPLAINATION_BODY_1 = "REPUTATION_POSITIVE_EXPLAINATION_BODY_1";

		public const string REPUTATION_POSITIVE_EXPLAINATION_BODY_2 = "REPUTATION_POSITIVE_EXPLAINATION_BODY_2";

		public const string REPUTATION_POSITIVE_EXPLAINATION_BODY_3 = "REPUTATION_POSITIVE_EXPLAINATION_BODY_3";

		public const string REPUTATION_POSITIVE_EXPLAINATION_FRIENDLY = "REPUTATION_POSITIVE_EXPLAINATION_FRIENDLY";

		public const string REPUTATION_POSITIVE_EXPLAINATION_TEAMWORK = "REPUTATION_POSITIVE_EXPLAINATION_TEAMWORK";

		public const string REPUTATION_POSITIVE_EXPLAINATION_HELPFUL = "REPUTATION_POSITIVE_EXPLAINATION_HELPFUL";
	}
}
