namespace LocalizationKeys
{
	public class ReputationColorExplaination
	{
		public const string REPUTATION_COLOR_EXPLAINATION_TITLE = "REPUTATION_COLOR_EXPLAINATION_TITLE";

		public const string REPUTATION_COLOR_EXPLAINATION_SAMPLE_PLAYER_NAME = "REPUTATION_COLOR_EXPLAINATION_SAMPLE_PLAYER_NAME";

		public const string REPUTATION_COLOR_EXPLAINATION_GREEN_TIER = "REPUTATION_COLOR_EXPLAINATION_GREEN_TIER";

		public const string REPUTATION_COLOR_EXPLAINATION_WHITE_TIER = "REPUTATION_COLOR_EXPLAINATION_WHITE_TIER";

		public const string REPUTATION_COLOR_EXPLAINATION_YELLOW_TIER = "REPUTATION_COLOR_EXPLAINATION_YELLOW_TIER";

		public const string REPUTATION_COLOR_EXPLAINATION_ORANGE_TIER = "REPUTATION_COLOR_EXPLAINATION_ORANGE_TIER";

		public const string REPUTATION_COLOR_EXPLAINATION_RED_TIER = "REPUTATION_COLOR_EXPLAINATION_RED_TIER";
	}
}
