namespace LocalizationKeys
{
	public class ReputationPunishment
	{
		public const string REPUTATION_PUNISHMENT_POPUP_TITLE = "REPUTATION_PUNISHMENT_POPUP_TITLE";

		public const string REPUTATION_PUNISHMENT_POPUP_SUBTITLE = "REPUTATION_PUNISHMENT_POPUP_SUBTITLE";

		public const string REPUTATION_PUNISHMENT_POPUP_BODY = "REPUTATION_PUNISHMENT_POPUP_BODY";

		public const string REPUTATION_PUNISHMENT_HINT_1 = "REPUTATION_PUNISHMENT_HINT_1";

		public const string REPUTATION_PUNISHMENT_HINT_2 = "REPUTATION_PUNISHMENT_HINT_2";

		public const string REPUTATION_PUNISHMENT_HINT_3 = "REPUTATION_PUNISHMENT_HINT_3";
	}
}
